title: WP CRM
description: Using WP-CRM you can create different frontend contact forms, expand the userâ€™s profile and monitoring their activity.
logo_image: https://storage.googleapis.com/media.usabilitydynamics.com/2014/11/0a6151b2-wpcrm-plugin-icon-300x300.png
wp_link: https://github.com/wp-crm/wp-crm

exclude:
  - node_modules
  - package.json
  - .idea
  - workspace.xml

sass:
  style: :compressed
  sass_dir: _sass
  load_paths:
    - node_modules
    - node_modules/**/*/node_modules

defaults:
  - scope:
      path: "addons"
    values:
      layout: addons
  - scope:
      path: "docs"
    values:
      layout: docs

branch: master
theme: jekyll-theme-minimal